import { useEffect, useRef } from "react";

/**
 * useScanner
 * Captures rapid keyboard input typically generated by barcode scanners.
 * Most scanners act as a keyboard and end with an "Enter" key.
 */
export function useScanner(onScan: (code: string) => void) {
  const bufferRef = useRef("");
  const lastKeyTimeRef = useRef(0);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const now = Date.now();
      
      // If the time between keys is too long, it's manual typing, so reset buffer
      // Barcode scanners usually have < 50ms between keys.
      if (now - lastKeyTimeRef.current > 50) {
        bufferRef.current = "";
      }
      
      lastKeyTimeRef.current = now;

      if (e.key === "Enter") {
        if (bufferRef.current.length > 2) {
          onScan(bufferRef.current);
        }
        bufferRef.current = "";
      } else {
        // Only capture alphanumeric characters
        if (e.key.length === 1 && /[a-zA-Z0-9]/.test(e.key)) {
          bufferRef.current += e.key;
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [onScan]);
}
